version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres.vbbwsozmfufbsylhjejz:z1RdKwf5O7VSIUVq@aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require"
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: change-me
    ports:
      - "5000:5000"
    depends_on:
      - redis
